version: '3.8'
services:
  mysql:
    container_name: ${PROJECT_NAME}-db
    image: 'mysql:5.7'
    volumes:
      - './mysqldb/data:/var/lib/mysql'
    ports:
      - '3308:3306'
    networks:
      backend:
        ipv4_address: 192.20.0.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    restart: always
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      backend:
        ipv4_address: 192.20.0.6
    depends_on:
      - mysql
    restart: always
  django_backend:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8085:8000
    expose:
      - 8000
    networks:
      backend:
        ipv4_address: 192.20.0.7
    depends_on:
      - mysql
    restart: always
networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.20.0.0/24